### PR TITLE
Add help page about markdown formatting #8

### PR DESCRIPTION
**Pull request by jackburg**
Add page with help about markdown formatting #8

### CODE REVIEW

**Comment by umputun** [comment]
Looks like it's missing a section about tables

**Comment by umputun** [comment]
And one more, bigger problem - this description is for developers, not for the regular humans :) Explaining in details how `-` converter to `<ul>` is kind of useless - someone aware of HTML formatting probably heard about markdown as well.  

Github https://guides.github.com/features/mastering-markdown/ and gitlab https://gitlab.com/help/user/markdown have much friendlier pages

**Comment by jackburg** [comment]
@umputun Ok, I need a little bit more time to complete with this doc. I'll try to accomplish this task due to the end of this week. BTW: Thank you for the links, it helps a lot.

**Comment by umputun** [comment]
something is not right with your PR. Not sure what is this, maybe you didn't merge/rebase first?

**Comment by jackburg** [comment]
@umputun I've squashed my current changes with my previous commit, and force push updates. BTW I had pulled (with rebase) all of the changes from the upstream, before the push.

**Comment by igoradamenko** [comment]
Hey @jackburg, thanks for your contribution. 

I've rebased & resolved conflicts here, and merged your markdown help in ab6bfff. Feel free to improve it later, if you have some time for that. 

For now I'm closing this PR. Thanks again 🐨

**Pull request closed without merging**
