### PR TITLE
Hide user comments

### PR DESCRIPTION
**Pull request by Reeywhaar**
to #291 

Adds ability to hide comments made by certain user.

Guest user:
Screenshot 2019-05-20 at 02 48 20

Logged in user:
Screenshot 2019-05-20 at 02 48 05

Admin:
Screenshot 2019-05-20 at 02 47 47

Right now it just plain button, there is no interface to manage hidden users. Also it's unclear what to do when user has logged out, and logged in as someone else — should list of hidden users be "per browser" or "per account"?

UPD: added settings interface for managing both hidden and blocked users, which replaces "blocked users" component

Screenshot 2019-06-10 at 01 30 46
--
Screenshot 2019-06-10 at 01 48 27
--
Screenshot 2019-06-10 at 01 50 26

There is no username in the list of blocked users right now because of #341, so just in case I've added "unknown"

### CODE REVIEW

**Comment by umputun** [comment]
> should list of hidden users be "per browser" or "per account"?

per browser fine

>  there is no interface to manage hidden users

smth as simple as a list of users and ability to "unhide", similar to "ui" for blocked users we have for admin, should be enough 

acva4_20190519_190101 oujzh

**Comment by Reeywhaar** [comment]
I think then both "blocked" and "hidden" manage buttons should be moved somewhere else, because "show hidden users" will be visible to guest and is bit confusing and I like how clear is interface when you not logged in. On second thought both these buttons can be visible only if user did actually hide or block someone. Also, these views should be merged. Also, I don't like that guest user has only one "hide" button in comment. Well, need to think on ui.

**Comment by umputun** [comment]
any progress with this one?

**Comment by Reeywhaar** [comment]
Unfortunately, I will not have time until next weekend

**Comment by Reeywhaar** [comment]
I see strange output of `/api/v1/admin/blocked`, `id` has value of `name`, and the name is `empty`
```
[{"id":"banned_joe","name":"","time":"2019-06-16T15:02:16.860926708-05:00"}]
```

?

**Comment by Reeywhaar** [comment]
filed an issue #341

**Comment by Reeywhaar** [comment]
updated PR

**Pull request merged**
