### PR TITLE
add Yandex OAuth provider #34

### PR DESCRIPTION
**Pull request by anatolym**
I added the Yandex OAuth provider, altered the UI and documentation, added unit-tests and check the Yandex login flow manually.
  The list of permissions has *Access to user avatar* and *Access to username, first name and surname, gender*. The latter is needed to get a friendly username. In fact a yandex user can have 3 different names:
  * `login` – same as first part of email address, this one is always required,
  * `real_name` – the combination of First and Last names, optional,
  * `display_name` – the name is used for displaying user name in yandex services, this name is visible to other yandex users.
  So more preferable name for us is `display_name`. If it's empty we use `real name`, otherwise `login`.
  The doc is here: https://tech.yandex.com/passport/doc/dg/reference/response-docpage/#norights_1

### CODE REVIEW

**Comment by umputun** [comment]
Thx for the PR. I'm not sure yet if we really need Yandex as another provider, but I'll think about it. Github related change will be nice to have as a separate PR and I could merge it right away.

**Comment by anatolym** [comment]
@umputun, got it. I will create another PR with github refactoring.

**Comment by umputun** [comment]
Regarding Yandex scope - is it possible to minimize it? We need just 3 things:

- some ID
- display name
- avatar

Things like first name and surname, gender, real name I'm trying to avoid, but not sure if it even possible with Yandex.

**Comment by umputun** [comment]
@igoradamenko can you take a look at js related part of this PR?

**Comment by umputun** [comment]
@anatolym could you resubmit with the recent master? We have a conflict on Gopkg.lock

**Comment by anatolym** [comment]
> Regarding Yandex scope - is it possible to minimize it? We need just 3 things:

@umputun, unfortunately nope. If we don't request the scope "Access to username, first name and surname, gender", we can use user `login` only. Display name comes together with gender and other stuff of the scope.
I'm not sure that's correct behavior since yandex users can hide `login` name on public services and use his Display name.

> could you resubmit with the recent master? We have a conflict on Gopkg.lock

Sure, gimme a minute.

**Comment by umputun** [comment]
thx, merged. Btw, if you could take care on twitter auth this will be really great.

**Comment by anatolym** [comment]
@umputun sure, I will take a look at twitter api.

**Pull request merged**
