### PR TITLE
Dark theme shows white preview #453

### PR DESCRIPTION
**Pull request by StaroKep**
Resolving #452 Dark theme shows white preview.

Hello! Please try and check that implementation.

@umputun @Reeywhaar

### CODE REVIEW

**Comment by umputun** [comment]
thx, LGTM

**Comment by StaroKep** [comment]
@umputun why the build failed?
[here](https://github.com/umputun/remark/runs/273956961)

**Comment by umputun** [comment]
Actions support still experimental

**Comment by StaroKep** [comment]
Oh. So, it's normal?

**Comment by umputun** [comment]
it has nothing to do with your PR for sure

**Comment by StaroKep** [comment]
OK, thx!

**Pull request merged**
