### PR TITLE
Dynamic comment's node watching

### PR DESCRIPTION
**Pull request by Reeywhaar**
Related to #220 

This PR adds ability for Remark to watch for comment's node adding/removing dynamically via MutationObserver. This solves the the problem I've stumbled while working on https://github.com/radio-t/rtnews-ui . It uses History API navigation, so remark's node can be added to the DOM not only at initial load, but at any time. To solve this, I had to copy/paste [`embed.js` and tweak it a bit](https://github.com/radio-t/rtnews-ui/blob/0ff0ea3547cc90b4e12aa2c5f34c6527664243d9/src/remark.jsx#L11-L264). This is not only looking ugly as hell, but also very inconvenient cause if Remark's node handling will change, I should recopy/repaste and apply tweaks again and maintain initialization/deinitialization myself.

Also, PR adds ability to define custom selector or straight HTMLElement, not only `#remark42`. This is useful, if you for example want set id to "#comments", or track by class.

**Downside:** Solution uses MutationObserver which watch for any hierarchy change in document.body. This could be useless if website is not dynamic. So, I added boolean `dynamic` flag set to `false` by default.
Also, if browser doesn't support Mutation observer, the user will be left with it as is.

**Backwards compatibility:** compatible

------
I [used plain array](https://github.com/Reeywhaar/remark/blob/4d0bef74df1d79a06cc93613cd9d80f2a905af09/web/app/embed.js#L233) to store initialized nodes info. But `WeakMap` is more suitable for such case, but it's support though is very good, but is still questionable, depending on which platforms do you plan to support, like ie10, 11?

------
I noticed that same logic may be applied to `counter` and `last comments` pages. So, I wonder, do I have a point with this pr, guys? Or maybe another approach could take place. Like Initializing global `Remark` object with `initNode`, `deinitNode` methods?

### CODE REVIEW

**Comment by umputun** [comment]
I still don't understand what exactly was the problem and what "to watch for comment's node adding/removing dynamically via MutationObserver" supposed to fix. Probably just my ignorance and all of frontend guys get it, but anyway ;)

**Comment by Reeywhaar** [comment]
Hehe, well, [History API](https://css-tricks.com/using-the-html5-history-api/) is a way for single page application to dynamically reuse current DOM without actual http navigation. Consider we visit [news.radio-t.com](http://news.radio-t.com) and click on some post [news.radio-t.com/post/some-post](http://news.radio-t.com/post/some-post). With history api server will get no `GET http://news.radio-t.com/post/some-post` request, since we didn't actually navigate from start page, we just reused current document, and replaced content dynamically with javascript.

So, the problem is that node `<div id="remark42">` appeared on the page after we declared remark [initialization script](https://github.com/umputun/remark#setup-on-your-website). Remark already failed with "no root found" error, and exited. That what I meant by "watch for comments node dynamically", remark should watch for node not only at start, but should track changes in DOM and apply init/deinit logic. That is what MutationObserver for. It's an API for watching changes in DOM, such as node adding/removing, change of node's attribute, etc...

I can modify pr to remove merge conflicts, but, hey @Guria, @igoradamenko what do you think about the whole situation? I said already that there could be multiple ways to implement api: first via `MutationObserver`, second manually via `window.REMARK.init(node)/window.REMARK.deinit(node)` methods.

**Comment by Guria** [comment]
@Reeywhaar Why not to use History API events instead of MutationObserver?

**Comment by Reeywhaar** [comment]
@Guria, changes in DOM not always caused by changes in history.

**Comment by Reeywhaar** [comment]
Revoking this pr, but question in #221 still stands.

**Comment by poohitan** [comment]
Why wasn't it merged?

**Pull request closed without merging**
