### PR TITLE
Add focus-visible polyfill, issue #187

### PR DESCRIPTION
**Pull request by Clearic**
1. Added focus-visible polyfill
2. Removed unnecessary `outline: none` from styles
3. Made buttons Pin, Block, Delete visible under focus

### CODE REVIEW

**Comment by Clearic** [comment]
@Guria I've fixed the shape of the outline.

This close button appears with an outline because it is outside of the iframe. I think we should not apply focus-visible polyfill outside of the iframe. I'd left it as it is right now.

**Comment by matrixik** [comment]
Sorry for possibly stupid question (I don't code in JS or CSS):
Why adding another JS script dependency for this functionality instead of some small CSS fixes?
Like in this user style: https://userstyles.org/styles/12981/highlight-every-focused-element-highlightfocus

**Comment by Clearic** [comment]
@matrixik we are not simply changing the style of focused elements here, we hide the outline of focused elements for mouse and touch users, but outline still should appear for keyboard users. Watch this video [Focus Ring! -- A11ycasts #16](https://www.youtube.com/watch?v=ilj2P5-5CjI&t=392s), it very well describes the problem we are solving here.

**Comment by Guria** [comment]
@umputun suggested to completely remove close button since you can click anywhere to hide overlay and listen to ESC-keypress event to close by keyboard. But close button must stay when overlay iframe completely covers the screen. @Clearic, what do you think about it?

**Comment by Clearic** [comment]
Making the close button appears only when popup completely covers the screen seems a bit complicated.

Let's just not focus the close button by default and instead focus the iframe itself, this way the focus ring just won't appear around the close button every time a user opens the user info.

**Comment by Clearic** [comment]
1) I've added the capability to close the User Info panel by hitting ESC. 
2) And the close button is not focused by default now.

**Pull request merged**
