### PR TITLE
Fix incorrect countdown timer calculation #74

### PR DESCRIPTION
**Pull request by jackburg**
This PR intended to fix (#74) issue.

Now when we download comments from the server, we calculating time span between server and a client and use it later when calculating time remaining for comment editing.

### CODE REVIEW

**Comment by Guria** [comment]
@jackburg I think there is no need to store `timeDiff` in every comment.
Let's just put it in redux store.

**Comment by jackburg** [comment]
@Guria ok, I've placed time diff into the store. Check it out.

**Comment by jackburg** [comment]
@umputun looks like some mongo tests are not passed as expected, could you please take a look?

**Comment by umputun** [comment]
This is odd. According to travis logs, it can't see `MONGO_TEST` and this is a relatively fresh change of master. However, it looks like you have merged the current master to your PR, so I don't really see what exactly confusing travis here. Can be something security related as they try to prevent malicious changes in CI file, but I don't see anything suspicious in your PR.

**Comment by umputun** [comment]
I can suggest to re-do your PR on top of the current master. hopefully, it will make travis happy

**Comment by jackburg** [comment]
Thanks, I'll try it.

**Comment by jackburg** [comment]
Out of luck. Maybe I should undo the merge as well? @Guria any advice?

**Comment by Guria** [comment]
Try to squash all commits into one

**Comment by jackburg** [comment]
@Guria Looks like I'm unable to squash them, because they've already been pushed.

**Comment by Guria** [comment]
You can use --force flag with push command

**Comment by jackburg** [comment]
@guria how many commits should I squash? Only mine, or including commit with the merge (with umputun changes)? What do you think?

**Comment by Guria** [comment]
Squash everything you see on Commits tab.
Next time to update your feature branch prefer rebase over merge from master.
Don't afraid to force push into feature branches.

**Comment by jackburg** [comment]
Got it, thank you.

**Comment by jackburg** [comment]
@Guria I've squashed all commits (btw I've many merge conflicts) and pushed the result with force flag, but still has this error, do you have any more advices?

**Pull request closed without merging**
