### PR TITLE
Resolve mobile navigation to comment issue #82

### PR DESCRIPTION
**Pull request by jackburg**
Fix issue #82

### CODE REVIEW

**Comment by umputun** [comment]
this failed on mongo tests as PR has no access to env in travis. I have defaulted those tests to `skip`, pls merge from the master and give it another try.

**Comment by jackburg** [comment]
@umputun, Ok I've merged these changes into the master and opened another PR #167

**Comment by umputun** [comment]
:( still failing, those envs are tricky for PRs. Could you pls do it one more time? Hopefully, it will pass this time

**Comment by jackburg** [comment]
Yep, should I create another PR, or just create a dummy commit?

**Comment by umputun** [comment]
you should merge first

**Comment by jackburg** [comment]
issue-82 branch into the master?

**Comment by jackburg** [comment]
Ah, I see…

**Comment by jackburg** [comment]
@umputun looks like everything is alright now, thank you for your help.

**Pull request closed without merging**
