### PR TITLE
Add email html template

### PR DESCRIPTION
**Pull request by Reeywhaar**
to https://github.com/umputun/remark/issues/349#issuecomment-508947861

I've added it as plain html file named "mail-templates/confirmation.html". Hope you would add it to build process.

Screenshot 2019-07-06 at 23 16 11

### CODE REVIEW

**Comment by umputun** [comment]
thx. I have added it directly, don't see a reason to convert from an external file as a part of build process

**Comment by umputun** [comment]
selection is kind of strange, not sure if expected
ab055-201907-06181255-fb0q0

**Comment by Reeywhaar** [comment]
hmm, what type of email client/browser?

**Comment by umputun** [comment]
just update my orig comment: airmail os mac os

**Comment by Reeywhaar** [comment]
Check please, safari shows its temper.

Also I've added easier select on token field

**Comment by umputun** [comment]
copied to the code

**Comment by Reeywhaar** [comment]
Let me know if it's fine and I'll close pr

**Comment by umputun** [comment]
perfect

**Pull request closed without merging**
