### PR TITLE
Do not render dummy for comment once it gets into viewport

### PR DESCRIPTION
**Pull request by Reeywhaar**
to #565

Stop rendering dummy block for comment once it appears in viewport

### CODE REVIEW

**Comment by paskal** [comment]
After this change comments page becomes searchable. However it's still searchable after changing the sort method, I was thinking that after sort change we should re-render everything from scratch to prevent performance issues.

**Comment by Reeywhaar** [comment]
Uhm, okay. I see two tropes:

first:
on sort change: we unmount whole tree (and show something like "loading..."). After remount comment state will be cleared and `renderDummy` will be `false` again.
pros:
- easy to do
cons:
- "loading..."

second:
we add `sortChangeCount` to redux and increment on each sort change. Then use `sortChangeCount` as part of thread's and comment's key. On key change, comment will be remounted.
pros:
- behaviour will be same as now
cons:
- err, need to manage count value and components keys.

Know something else?

**Comment by paskal** [comment]
FYI: I am completely happy with how it works now (search on-page problem is solved) and I don't see performance downsides on 42 comments I've created.

I'm asking about the sort because you mentioned that it will be slow on a bigger dataset, and I was under impression that it's relatively cheap to have current performance benefits and at the same time fix page search problem, however from what I see at this very moment and from what I've read from your explanations, this PR seems to be eliminating performance benefits for someone who loaded the whole page. I might be completely wrong about it, it's just a guess from the information I have as someone who don't know how it works inside.

**Comment by Reeywhaar** [comment]
I am not sure If I should change anything else as well. I do not know what expected behaviour for user after sort change (search will not be working again).

Btw, I see someone updated react-redux library (which I tried to avoid, because at some version there appeared lags between user actions), and now I feel every click has some lag. There is some difficulties caused by using of preact. Am I the one who notices it?

**Comment by paskal** [comment]
> I do not know what expected behaviour for user after sort change (search will not be working again).

In analogy to Reddit, I would expect it to load first ~50 comments with a new sort method and everything I've seen so far to be lost for search and re-appear only after I start scrolling the page again.

**Comment by akellbl4** [comment]
@Reeywhaar I can't see lags but maybe because I didn't see when it was better.

Also, I saw the discussion connected with adding redux in the project, and I think redux unnecessary for the project especially now when we can change it by `useReducer` and theme interface by CSS vars. I think it can be a theme for a new discussion about that.

I will check which place can cause problems with performance because I don't see any problems with it in my projects which operate with a bigger data storage.

**Pull request merged**
