### PR TITLE
reveal node_modules in separate container

### PR DESCRIPTION
**Pull request by Guria**
This allows to reuse docker fs layer with node_modules
in case if there were no changes in package*.json
As a result it decreases dependency on network and build times
in rebuilds at least in local environment.

### CODE REVIEW

**Comment by Guria** [comment]
related to https://github.com/umputun/remark/issues/119#issuecomment-401595070

**Comment by Guria** [comment]
To get fs layer reuse in CI we might tweak our setup like described at https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326

**Comment by umputun** [comment]
This is an interesting idea, but I'm not sure about that travis part. You can add travis's change to this PR, and we could see how it works. The second part - we will need smth similar for drone. And the last part I don't know if such complexity even justified. Initially, in #119 I hoped to make frontend build dependency vendored directly, which seems to be non-trivial. However, if the change also decreases build time (significantly), it could be another good reason,

**Comment by Guria** [comment]
@umputun Is there a way to see build log from drone.io? I tried to open link, but it says just Loading. Login attempt is also failed. Btw, what it used for?

It seems like drone.io have better docker integration and maybe it would be simpler setup.

**Comment by Guria** [comment]
It seems travis config didn't helped.

**Comment by umputun** [comment]
@Guria I think travis won't allow PR change for the `.travis.yml` due to security concerns. The only way to test it is your own travis against forked repo.

**Comment by Guria** [comment]
@umputun after series of experiments I decided to stop experimenting with enabling docker fs layer caching on CI. It seems like overhead on cache packing/unpacking is more then potential win in build time.
I also introduced custom image with git and cached binary for node-sass. It used only in step that collects node_modules. Build container is still based on official image.

**Comment by umputun** [comment]
> I also introduced custom image with git and cached binary for node-sass

I don't like the new dependency on `guria/build-node:latest` as a part of our build process. If this image base-enough to be added to  https://github.com/umputun/baseimage - pls PR to that repo.

**Comment by Guria** [comment]
@umputun  removed custom dependency since we don't rely on node-sass binary anymore

This doesn't improve anything on CI. But it's very useful for local development since it speeds up build times and saves network bandwidth, especially on limited mobile connections.

**Comment by umputun** [comment]
LGTM

**Pull request merged**
