### PR TITLE
Increase margins in email auth popup

### PR DESCRIPTION
**Pull request by Reeywhaar**
to https://github.com/umputun/remark/issues/349#issuecomment-508960807
Screenshot 2019-07-07 at 03 10 21

### CODE REVIEW

**Comment by umputun** [comment]
gz857-201907-06201624-3g3ek

**Comment by Reeywhaar** [comment]
Elaborate?

**Comment by umputun** [comment]
this missing bottom part of the frame is not a partial screenshot, but the actual view if no comments

**Comment by Reeywhaar** [comment]
Oh... Do you like the idea to add some "No comments there yet", which will add some vertical space? :-)

**Comment by umputun** [comment]
not really :) Maybe just a little bit of space without any text

**Pull request merged**
