### PR TITLE
Some DB errors is not errors

### PR DESCRIPTION
**Pull request by kazhuravlev**
get comment by id on non exists id or non exists bucket:
`HTTP 400 + err` => `HTTP 404`

get comments list on non exists page bucket, userID bucket:
`HTTP 400 + err` => `HTTP 200 + blank comment list "[]"`

### CODE REVIEW

**Comment by kazhuravlev** [comment]
one of tests is failed. but this test also failed on master branch (`TestRemark_Export`). 
I fix this err in this PR

**Comment by kazhuravlev** [comment]
@umputun please show me error cause. 
on my side all tests, linter checks and docker-compose build is worked fine.

**Comment by umputun** [comment]
until we switch to public CI (see #14) the only way to see what failed the build the same way as CI is to run docker build.

```
app/store/engine/bolt.go:217::warning: declaration of "err" shadows declaration at app/store/engine/bolt.go:210 (vetshadow)
28s
516
app/store/engine/bolt.go:488::warning: declaration of "err" shadows declaration at app/store/engine/bolt.go:477 (vetshadow)
28s
517
app/rest/api/rest.go:354:10:warning: if block ends with a return statement, so drop this else and outdent its block (golint)
28s
518

```

**Comment by umputun** [comment]
I'm not sure what the purpose of this PR. What exactly the problem it's trying to solve by adding all this code? I mean, I get what it's trying to achieve is to differentiate store errors with more granularity, but don't get why all of this even needed in the first place.

Do you have any particular use-case in mind? To me, requests for non-exiting id, bucket, and the user feels like a good fit for "bad request".

**Comment by kazhuravlev** [comment]
I do not speak English well. I hope you understand me:
I think that client must be simple as possible. Client can not process bad request errors. But client must work with comments API as with faceted search.

close until #14 ))

**Pull request closed without merging**
