### PR TITLE
add widgets to demo page

### PR DESCRIPTION
**Pull request by Reeywhaar**
To https://github.com/umputun/remark/issues/261#issuecomment-457727198

Added widgets to demo page:
screenshot 2019-01-26 at 00 51 54

### CODE REVIEW

**Comment by umputun** [comment]
confused with multiple counters. what is the first? what is the second?

**Comment by Reeywhaar** [comment]
Is that better? I think the whole demo page can be made better (add links to docs and so on), so it's just a quick and dirty, right now.
screenshot 2019-01-26 at 01 36 27

**Comment by umputun** [comment]
LGTM

**Comment by umputun** [comment]
do you want me to merge or want me to wait till you undirtify this?

**Comment by Reeywhaar** [comment]
I think you can merge it, so you can solve #261 

I can calmly then think about what it page needs.

**Comment by umputun** [comment]
thx!

**Comment by Reeywhaar** [comment]
@umputun np

@igoradamenko maybe help me with this one, if have some free time? I am no designer at all, and I think you better understand what should be done here :-)

**Pull request merged**
