### PR TITLE
support new voting api in ui

### PR DESCRIPTION
**Pull request by Reeywhaar**
to #297 

Adds ui support for new voting api.

Backend side doesn't seem to work, `vote` is always 0.

### CODE REVIEW

**Comment by umputun** [comment]
did you test with `vote` branch?

**Comment by Reeywhaar** [comment]
Yep, though I have tested against db left from 'anon users' branch, not with a new one. [remark.db.zip](https://github.com/umputun/remark/files/3051936/remark.db.zip)

**Comment by umputun** [comment]
this is odd. I had a rich set of tests covering as much related to new `vote` functionality as I can think of and even added more. Pls note (just in case) - `vote` is visible (i.e. non-zero) for a regular (not an anonymous) authenticated user only and only for his own votes.

**Comment by Reeywhaar** [comment]
oh, I've found the problem, I fetch 'GET' data without sending credentials.

**Comment by umputun** [comment]
one more thing - the build failed due to some strange changes on travis side causing very slow start of tests. This had been addressed on master, but vote bench will fail.

**Comment by umputun** [comment]
>  I fetch 'GET' data without sending credentials.

does it mean UI is working, but some manual tests you did with curl failed?

**Comment by Reeywhaar** [comment]
Yeah, UI working, but comments fetched as from anonymous user.

**Comment by Reeywhaar** [comment]
Updated pr.

Now something strange happening. There is like some sort of caching in `/api/v1/find` endpoint. If I login, upvote someone, then logout, and refresh comments (clean cookie, no XSRF, etc), response still contains `vote` on comment that I upvoted. Then if I login again, and upvote another comment, state seems to be updated to correct one, or to current–1 version :/

Screenshot 2019-04-08 at 01 19 37

```
GET /api/v1/find?site=remark&url=https://remark42.com/demo/&sort=-active&format=tree HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: ///
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:9000/web/iframe.html?site_id=remark&url=https%3A%2F%2Fremark42.com%2Fdemo%2F
Content-Type: application/json
X-XSRF-TOKEN: 
DNT: 1
Connection: keep-alive
```

**Comment by umputun** [comment]
This was an unexpected side effect of the introduced state. For now, I have added another element to the caching key making the cache user-specific but this is strange solutions as per-user cache for find doesn't make much sense. 

All of this seems to work correctly now (pls check too), however, I'll need to figure a better way to alter cached response with proper support of `vote` flag

**Comment by Reeywhaar** [comment]
Rebased on top of your recent commits. Seems to be working fine.

**Pull request merged**
