### PR TITLE
Email auth ui

### PR DESCRIPTION
**Pull request by Reeywhaar**
to #349 

Adds email auth ui

Screenshot 2019-07-06 at 19 52 00

Screenshot 2019-07-06 at 19 51 49

Screenshot 2019-07-06 at 19 54 43

### CODE REVIEW

**Comment by umputun** [comment]
Thx. A couple of things:

- the token is a long line, maybe we should show text box instead of a single input line and autowrap?
- I have merged email branch to master, pls PR to this one

**Comment by Reeywhaar** [comment]
how about this one?
Screenshot 2019-07-06 at 21 08 58
Screenshot 2019-07-06 at 21 09 06

**Comment by umputun** [comment]
nice. btw, one thing I have noticed - this dialog is not modal, and by clicking any place on the page by accident we could lose it. Maybe make it modal and add "close/cancel/X" ?

**Comment by Reeywhaar** [comment]
It saves state, so I think it's unnecessary. Adding "x" will require to tinker the whole design. Let me think about it.

**Comment by umputun** [comment]
does it save the state? On token confirmation, I have lost the focus and closed the popup by accident. As a clicked on "Email" again got to the name/email entry part with everything empty

**Comment by umputun** [comment]
let me know as we good to merge. I have prepared email server and configured demo box to support email auth

**Comment by Reeywhaar** [comment]
It's not? It should. Except it loses data on page reload (maybe I should keep it in local storage). Other than that we good to merge.

ezgif-2-4b9da0709a4b

**Pull request merged**
