### PR TITLE
Add frontend support for anonymous user login

### PR DESCRIPTION
**Pull request by Reeywhaar**
to #279 

depends on #281 

Adds support for anonymous user login

anon-screencap

### CODE REVIEW

**Comment by umputun** [comment]
This is a scary looking one ;) It seems to include all refactoring, i.e. on top of #281. I think we should finalize refactoring and rebase on top if it

**Comment by umputun** [comment]
another thing on my side - probably it makes sense to set dev-style avatar (identicon) for anonymous users

**Comment by Reeywhaar** [comment]
Yep, when refactoring will be merged I think github should start to show commits on base of refactoring top.

I've made [anonymous avatar](https://github.com/Reeywhaar/remark/blob/feature/front-anon-login/web/app/components/avatar-icon/anonymous-icon.svg) in style of [lost avatar](https://github.com/Reeywhaar/remark/blob/feature/front-anon-login/web/app/components/avatar-icon/avatar-icon.svg), but yeah, better to show different icons.

**Comment by umputun** [comment]
Can you add anon to your demo page on go-pkgz/auth pls? This way I will able to see it in action

**Comment by Reeywhaar** [comment]
@umputun let me know when you add identicon support. I need to handle it as well, as now in case of anonymous login predefined icon displayed.

**Comment by umputun** [comment]
should be in place - released v0.5.0 of `pkgz/auth` and updated dependency here.

**Comment by Reeywhaar** [comment]
Updated to use identicons.

**Comment by umputun** [comment]
ping ping. @igoradamenko / @Guria - any chance you can review this one, pleeease?

**Comment by Reeywhaar** [comment]
Well, I'm myself busy until next weekend probably, so #297, #291, #285 etc... will have to wait if no one wishes to participate.

**Comment by Guria** [comment]
@umputun will take a look this week

**Pull request merged**
