### PR TITLE
Fix ui errors (preview and image upload)

### PR DESCRIPTION
**Pull request by Reeywhaar**
to #346 

Apparently not only preview was broken, but image upload too :-)

I missed the thing that I was trying to connect functions which are not `actions`, but straight api calls via react-redux `connect`.

### CODE REVIEW

**Comment by umputun** [comment]
Thx a lot. Is this thing can be tested automatically somehow?

**Comment by Reeywhaar** [comment]
You mean end-to-end? Sounds interesting, in fact, as whole app is dockerized. Right now, unit-testing is barely exists, and I need to to think about the harness. As of now we test only plain `not-connected` components, and not the intermediate connection of api and components.

**Comment by umputun** [comment]
I don't think the issue was fixed :( On demo site, it seems to work, but getting errors  on radio-t

pkfmj-201906-16161052-tj979

**Comment by Reeywhaar** [comment]
Hmmm, how can I reproduce?

**Comment by umputun** [comment]
whatever it seems to happen in safari, chorme is fine

**Comment by umputun** [comment]
I got it by typing a new comment and clicking Preview

**Comment by umputun** [comment]
hmm, maybe it just me/caching? not sure. Tried to reload the page multiple time and it started to work. So, maybe it was fixed ;)

**Comment by Reeywhaar** [comment]
Seems to be cache issues, safari likes it. We don't have any cache policy, neither `Cache-Control`, nor `Etag`

**Comment by Reeywhaar** [comment]
Oh, we have `Last-Modified`, but safari seems to ignore it

**Comment by umputun** [comment]
> You mean end-to-end?

Not sure, have no clue what type of tests can be done on UI side. If end-to-end is the only way so be it.

**Pull request merged**
